program: train.py
method: bayes
metric:
  goal: minimize
  name: wer
parameters:
  learning_rate:
    max: 0.001
    min: 0.0001
    distribution: uniform
  gradient_accumulation_steps:
    max: 32
    min: 8
    distribution: int_uniform
  num_train_epochs:
    max: 2
    min: 1
    distribution: uniform
  weight_decay:
    values: [0.01, 0.1, 0.2]
    distribution: categorical
  warmup_ratio:
    values: [0.1, 0.05]
    distribution: categorical
  lora_r:
    max: 64
    min: 8
    distribution: int_uniform
  lora_alpha:
    max: 34
    min: 4
    distribution: int_uniform
  lora_dropout:
    max: 0.1
    min: 0.01
    distribution: uniform
  bf16_full_eval:
    values: ["true", "false"]
    distribution: categorical
